# This file is equivalent to Jenkinsfile in jenkins, workflow in github acitons
############################################################
steps:
# Take me a cloud builder image with docker installled
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/project-fe6816d0-c7fc-4c9b-bd7/docker-repo/my-app:v1', '.']
# Push the image to artifact registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/project-fe6816d0-c7fc-4c9b-bd7/docker-repo/my-app:v1']
# Deploy image to cloud run 
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'my-app', '--image', 'us-central1-docker.pkg.dev/project-fe6816d0-c7fc-4c9b-bd7/docker-repo/my-app:v1', '--region', 'us-central1', '--allow-unauthenticated']
