steps: 
# Build the Docker image 
# docker build -t us-central1-docker.pkg.dev/proven-wavelet-481608-k1/docker-images/app:v1 .
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/proven-wavelet-481608-k1/docker-images/app:v1', 'build-run/.']
# Push the image to Google Artifact Registry 
# docker push us-central1-docker.pkg.dev/proven-wavelet-481608-k1/docker-images/app:v1
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/proven-wavelet-481608-k1/docker-images/app:v1']
# Deploy the image to cloud run 
# gcloud run deploy python-app --image us-central1-docker.pkg.dev/proven-wavelet-481608-k1/docker-images/app:v1 --region us-central1 --allow-unauthenticated 
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'python-app', '--image',
        'us-central1-docker.pkg.dev/proven-wavelet-481608-k1/docker-images/app:v1',
        '--region', 'us-central1', '--allow-unauthenticated']
options:
  logging: CLOUD_LOGGING_ONLY
